/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ets;

import java.awt.Insets;
/**
 *
 * @author sahar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayoutManager = new javax.swing.JPanel();
        LoginPage = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LoginHeading = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LoginUsername = new javax.swing.JLabel();
        LoginUsernameField = new javax.swing.JTextField();
        LoginPassword = new javax.swing.JLabel();
        LoginPasswordField = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        SignupButton = new javax.swing.JButton();
        LoginBackground = new javax.swing.JLabel();
        RegistrationPage = new javax.swing.JPanel();
        RegistrationPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        RegistrationHeading = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        jPanel9 = new javax.swing.JPanel();
        SignUpButton = new javax.swing.JButton();
        BackToLoginButtton = new javax.swing.JButton();
        RegistrationBackground = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPanel13 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        RegistrationPage2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPanel17 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        RegistrationPage3 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPasswordField5 = new javax.swing.JPasswordField();
        jPanel21 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        RegistrationPage4 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPasswordField6 = new javax.swing.JPasswordField();
        jPanel25 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expense Tracking System");
        setAlwaysOnTop(true);
        setName("Frame1"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1094, 756));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));

        LayoutManager.setPreferredSize(new java.awt.Dimension(1080, 720));
        LayoutManager.setLayout(new java.awt.CardLayout());

        LoginPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setBorder(new RoundedBorder(30));
        LoginPanel.setToolTipText("");
        LoginPanel.setOpaque(false);
        LoginPanel.setPreferredSize(new java.awt.Dimension(400, 600));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setOpaque(false);

        LoginHeading.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        LoginHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginHeading.setText("Hey, Hello!");
        LoginHeading.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(LoginHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LoginPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        jPanel5.setBackground(new java.awt.Color(255, 102, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        LoginUsername.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LoginUsername.setForeground(new java.awt.Color(153, 153, 153));
        LoginUsername.setText("Username");
        jPanel5.add(LoginUsername);

        LoginUsernameField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LoginUsernameField.setForeground(new java.awt.Color(204, 204, 204));
        LoginUsernameField.setToolTipText("");
        LoginUsernameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        LoginUsernameField.setMargin(new java.awt.Insets(2, 50, 2, 6));
        LoginUsernameField.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel5.add(LoginUsernameField);

        LoginPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LoginPassword.setForeground(new java.awt.Color(153, 153, 153));
        LoginPassword.setText("Password");
        jPanel5.add(LoginPassword);

        LoginPasswordField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LoginPasswordField.setForeground(new java.awt.Color(204, 204, 204));
        LoginPasswordField.setToolTipText("");
        LoginPasswordField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        LoginPasswordField.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel5.add(LoginPasswordField);

        LoginPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 300, 152));

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        LoginButton.setBackground(new java.awt.Color(0, 0, 0));
        LoginButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Log in");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel6.add(LoginButton);

        SignupButton.setBackground(new java.awt.Color(254, 254, 254));
        SignupButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        SignupButton.setText("Sign up");
        SignupButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });
        jPanel6.add(SignupButton);

        LoginPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 385, 300, 103));

        LoginPage.add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        LoginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_gradient.jpg"))); // NOI18N
        LoginPage.add(LoginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        LayoutManager.add(LoginPage, "card2");

        RegistrationPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrationPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegistrationPanel.setBorder(new RoundedBorder(30));
        RegistrationPanel.setToolTipText("");
        RegistrationPanel.setOpaque(false);
        RegistrationPanel.setPreferredSize(new java.awt.Dimension(400, 600));
        RegistrationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setOpaque(false);

        RegistrationHeading.setFont(new java.awt.Font("Berlin Sans FB", 0, 40)); // NOI18N
        RegistrationHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegistrationHeading.setText("Signing you up...");
        RegistrationHeading.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrationHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(RegistrationHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RegistrationPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        jPanel8.setBackground(new java.awt.Color(255, 102, 255));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(0, 1));

        Name.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(153, 153, 153));
        Name.setText("Full Name");
        jPanel8.add(Name);

        NameField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        NameField.setForeground(new java.awt.Color(204, 204, 204));
        NameField.setToolTipText("");
        NameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        NameField.setMargin(new java.awt.Insets(2, 50, 2, 6));
        NameField.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel8.add(NameField);

        Email.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(153, 153, 153));
        Email.setText("Email");
        jPanel8.add(Email);

        EmailField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        EmailField.setForeground(new java.awt.Color(204, 204, 204));
        EmailField.setToolTipText("");
        EmailField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        EmailField.setMargin(new java.awt.Insets(2, 50, 2, 6));
        EmailField.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel8.add(EmailField);

        Username.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(153, 153, 153));
        Username.setText("Username");
        jPanel8.add(Username);

        UsernameField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(204, 204, 204));
        UsernameField.setToolTipText("");
        UsernameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        UsernameField.setMargin(new java.awt.Insets(2, 50, 2, 6));
        UsernameField.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel8.add(UsernameField);

        Password.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(153, 153, 153));
        Password.setText("Password");
        jPanel8.add(Password);

        PasswordField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(204, 204, 204));
        PasswordField.setToolTipText("");
        PasswordField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        PasswordField.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel8.add(PasswordField);

        ConfirmPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ConfirmPassword.setForeground(new java.awt.Color(153, 153, 153));
        ConfirmPassword.setText("Confirm Password");
        jPanel8.add(ConfirmPassword);

        ConfirmPasswordField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ConfirmPasswordField.setForeground(new java.awt.Color(204, 204, 204));
        ConfirmPasswordField.setToolTipText("");
        ConfirmPasswordField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        ConfirmPasswordField.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel8.add(ConfirmPasswordField);

        RegistrationPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 125, 300, 300));

        jPanel9.setBackground(new java.awt.Color(255, 102, 102));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        SignUpButton.setBackground(new java.awt.Color(0, 0, 0));
        SignUpButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        jPanel9.add(SignUpButton);

        BackToLoginButtton.setBackground(new java.awt.Color(254, 254, 254));
        BackToLoginButtton.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        BackToLoginButtton.setText("Back to login");
        BackToLoginButtton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BackToLoginButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLoginButttonActionPerformed(evt);
            }
        });
        jPanel9.add(BackToLoginButtton);

        RegistrationPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 300, 90));

        RegistrationPage.add(RegistrationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        RegistrationBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_gradient.jpg"))); // NOI18N
        RegistrationPage.add(RegistrationBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        LayoutManager.add(RegistrationPage, "card3");

        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new RoundedBorder(30));
        jPanel10.setToolTipText("");
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));
        jPanel11.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Hey, Hello!");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        jPanel12.setBackground(new java.awt.Color(255, 102, 255));
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(0, 1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Username");
        jPanel12.add(jLabel10);

        jTextField3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setToolTipText("");
        jTextField3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        jTextField3.setMargin(new java.awt.Insets(2, 50, 2, 6));
        jTextField3.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel12.add(jTextField3);

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Password");
        jPanel12.add(jLabel11);

        jPasswordField3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField3.setToolTipText("");
        jPasswordField3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        jPasswordField3.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel12.add(jPasswordField3);

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 300, 152));

        jPanel13.setBackground(new java.awt.Color(255, 102, 102));
        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Log in");
        jPanel13.add(jButton5);

        jButton6.setBackground(new java.awt.Color(254, 254, 254));
        jButton6.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jButton6.setText("Sign up");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel13.add(jButton6);

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 385, 300, 103));

        Dashboard.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1020, 660));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_gradient.jpg"))); // NOI18N
        Dashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        LayoutManager.add(Dashboard, "card3");

        RegistrationPage2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new RoundedBorder(30));
        jPanel14.setToolTipText("");
        jPanel14.setOpaque(false);
        jPanel14.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(153, 204, 255));
        jPanel15.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hey, Hello!");
        jLabel13.setToolTipText("");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        jPanel16.setBackground(new java.awt.Color(255, 102, 255));
        jPanel16.setOpaque(false);
        jPanel16.setLayout(new java.awt.GridLayout(0, 1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Username");
        jPanel16.add(jLabel14);

        jTextField4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setToolTipText("");
        jTextField4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        jTextField4.setMargin(new java.awt.Insets(2, 50, 2, 6));
        jTextField4.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel16.add(jTextField4);

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Password");
        jPanel16.add(jLabel15);

        jPasswordField4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPasswordField4.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField4.setToolTipText("");
        jPasswordField4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        jPasswordField4.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel16.add(jPasswordField4);

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 300, 152));

        jPanel17.setBackground(new java.awt.Color(255, 102, 102));
        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Log in");
        jPanel17.add(jButton7);

        jButton8.setBackground(new java.awt.Color(254, 254, 254));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jButton8.setText("Sign up");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel17.add(jButton8);

        jPanel14.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 385, 300, 103));

        RegistrationPage2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_gradient.jpg"))); // NOI18N
        RegistrationPage2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        LayoutManager.add(RegistrationPage2, "card3");

        RegistrationPage3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(new RoundedBorder(30));
        jPanel18.setToolTipText("");
        jPanel18.setOpaque(false);
        jPanel18.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(153, 204, 255));
        jPanel19.setOpaque(false);

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Hey, Hello!");
        jLabel17.setToolTipText("");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        jPanel20.setBackground(new java.awt.Color(255, 102, 255));
        jPanel20.setOpaque(false);
        jPanel20.setLayout(new java.awt.GridLayout(0, 1));

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Username");
        jPanel20.add(jLabel18);

        jTextField5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(204, 204, 204));
        jTextField5.setToolTipText("");
        jTextField5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        jTextField5.setMargin(new java.awt.Insets(2, 50, 2, 6));
        jTextField5.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel20.add(jTextField5);

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Password");
        jPanel20.add(jLabel19);

        jPasswordField5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPasswordField5.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField5.setToolTipText("");
        jPasswordField5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        jPasswordField5.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel20.add(jPasswordField5);

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 300, 152));

        jPanel21.setBackground(new java.awt.Color(255, 102, 102));
        jPanel21.setOpaque(false);
        jPanel21.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Log in");
        jPanel21.add(jButton9);

        jButton10.setBackground(new java.awt.Color(254, 254, 254));
        jButton10.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jButton10.setText("Sign up");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel21.add(jButton10);

        jPanel18.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 385, 300, 103));

        RegistrationPage3.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_gradient.jpg"))); // NOI18N
        RegistrationPage3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        LayoutManager.add(RegistrationPage3, "card3");

        RegistrationPage4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(new RoundedBorder(30));
        jPanel22.setToolTipText("");
        jPanel22.setOpaque(false);
        jPanel22.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBackground(new java.awt.Color(153, 204, 255));
        jPanel23.setOpaque(false);

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Hey, Hello!");
        jLabel21.setToolTipText("");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        jPanel24.setBackground(new java.awt.Color(255, 102, 255));
        jPanel24.setOpaque(false);
        jPanel24.setLayout(new java.awt.GridLayout(0, 1));

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("Username");
        jPanel24.add(jLabel22);

        jTextField6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(204, 204, 204));
        jTextField6.setToolTipText("");
        jTextField6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        jTextField6.setMargin(new java.awt.Insets(2, 50, 2, 6));
        jTextField6.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel24.add(jTextField6);

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Password");
        jPanel24.add(jLabel23);

        jPasswordField6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPasswordField6.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField6.setToolTipText("");
        jPasswordField6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 1)));
        jPasswordField6.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel24.add(jPasswordField6);

        jPanel22.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 300, 152));

        jPanel25.setBackground(new java.awt.Color(255, 102, 102));
        jPanel25.setOpaque(false);
        jPanel25.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Log in");
        jPanel25.add(jButton11);

        jButton12.setBackground(new java.awt.Color(254, 254, 254));
        jButton12.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jButton12.setText("Sign up");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel25.add(jButton12);

        jPanel22.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 385, 300, 103));

        RegistrationPage4.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_gradient.jpg"))); // NOI18N
        RegistrationPage4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        LayoutManager.add(RegistrationPage4, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayoutManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayoutManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 4350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        LoginPage.setVisible(false);
        RegistrationPage.setVisible(true);
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void BackToLoginButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLoginButttonActionPerformed
        RegistrationPage.setVisible(false);
        LoginPage.setVisible(true);
    }//GEN-LAST:event_BackToLoginButttonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        LoginPage.setVisible(false);
        Dashboard.setVisible(true);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        RegistrationPage.setVisible(false);
        Dashboard.setVisible(true);
    }//GEN-LAST:event_SignUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToLoginButtton;
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailField;
    private javax.swing.JPanel LayoutManager;
    private javax.swing.JLabel LoginBackground;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginHeading;
    private javax.swing.JPanel LoginPage;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LoginPassword;
    private javax.swing.JPasswordField LoginPasswordField;
    private javax.swing.JLabel LoginUsername;
    private javax.swing.JTextField LoginUsernameField;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel RegistrationBackground;
    private javax.swing.JLabel RegistrationHeading;
    private javax.swing.JPanel RegistrationPage;
    private javax.swing.JPanel RegistrationPage2;
    private javax.swing.JPanel RegistrationPage3;
    private javax.swing.JPanel RegistrationPage4;
    private javax.swing.JPanel RegistrationPanel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}


